# Generated by Django 4.1.13 on 2023-12-06 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0005_alter_offer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='responders',
            field=models.ManyToManyField(blank=True, null=True, related_name='responders', to=settings.AUTH_USER_MODEL, verbose_name='откликнулись'),
        ),
    ]
