# Generated by Django 4.1.13 on 2023-12-11 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_alter_offer_responders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['id', 'title'], 'verbose_name': 'заявка', 'verbose_name_plural': 'заявки'},
        ),
        migrations.AddField(
            model_name='offer',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата публикации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(upload_to='offers/%Y/%m/', verbose_name='фото'),
        ),
    ]
