# Generated by Django 4.1.13 on 2023-12-06 19:32

from django.db import migrations

def fill_locations(apps, schema_editor):
    countries = [
        {'code': 'RUS', 'flag': 'rus.png', 'name': 'Россия'},
        {'code': 'BLR', 'flag': 'blr.png', 'name': 'Беларусь'},
        {'code': 'KAZ', 'flag': 'kaz.png', 'name': 'Казахстан'},
        {'code': 'KGZ', 'flag': 'kgz.png', 'name': 'Киргизия'},
        {'code': 'CHN', 'flag': 'chn.png', 'name': 'Китай'},
        {'code': 'ERI', 'flag': 'eri.png', 'name': 'Эритрея'}
    ]

    cities = [
        {'country': 'RUS', 'name': 'Москва'},
        {'country': 'RUS', 'name': 'Санкт-Петербург'},
        {'country': 'RUS', 'name': 'Новосибирск'},
        {'country': 'RUS', 'name': 'Екатеринбург'},
        {'country': 'RUS', 'name': 'Нижний Новгород'},
        {'country': 'RUS', 'name': 'Казань'},
        {'country': 'RUS', 'name': 'Пенза'},
        {'country': 'RUS', 'name': 'Саранск'},
        {'country': 'RUS', 'name': 'Самара'},
        {'country': 'RUS', 'name': 'Саратов'},
        {'country': 'RUS', 'name': 'Владивосток'},
        {'country': 'RUS', 'name': 'Красноярск'},

        {'country': 'BLR', 'name': 'Минск'},
        {'country': 'BLR', 'name': 'Гомель'},
        {'country': 'BLR', 'name': 'Могилев'},
        {'country': 'BLR', 'name': 'Витебск'},
        {'country': 'BLR', 'name': 'Гродно'},
        {'country': 'BLR', 'name': 'Брест'},

        {'country': 'KAZ', 'name': 'Алматы'},
        {'country': 'KAZ', 'name': 'Астана'},
        {'country': 'KAZ', 'name': 'Шымкент'},
        {'country': 'KAZ', 'name': 'Караганда'},
        {'country': 'KAZ', 'name': 'Актобе'},
        {'country': 'KAZ', 'name': 'Тараз'},

        {'country': 'KGZ', 'name': 'Бишкек'},
        {'country': 'KGZ', 'name': 'Ош'},
        {'country': 'KGZ', 'name': 'Джалал-Абад'},
        {'country': 'KGZ', 'name': 'Каракол'},
        {'country': 'KGZ', 'name': 'Токмок'},
        {'country': 'KGZ', 'name': 'Кара-Балта'},

        {'country': 'CHN', 'name': 'Шанхай'},
        {'country': 'CHN', 'name': 'Пекин'},
        {'country': 'CHN', 'name': 'Гуанчжоу'},
        {'country': 'CHN', 'name': 'Шэньчжэнь'},
        {'country': 'CHN', 'name': 'Тяньцзинь'},
        {'country': 'CHN', 'name': 'Чунцин'},

        {'country': 'ERI', 'name': 'Асмэра'},
        {'country': 'ERI', 'name': 'Кассала'},
        {'country': 'ERI', 'name': 'Массауа'},
        {'country': 'ERI', 'name': 'Асаб'},
        {'country': 'ERI', 'name': 'Керен'},
        {'country': 'ERI', 'name': 'Барен'}
    ]

    for country in countries:
        Country = apps.get_model('locations', 'Country')
        City = apps.get_model('locations', 'City')

        new_country = Country.objects.create()
        new_country.code = country['code']
        new_country.flag = country['flag']
        new_country.name = country['name']
        new_country.save()

        for city in cities:
            if city['country'] == new_country.code:
                new_city = City()
                new_city.country = new_country
                new_city.name = city['name']
                new_city.save()

class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_locations),
    ]
